version: '3'
services:
  app:
    image: node:latest
    environment:
      - API_GATEWAY_URL
      - NPM_TOKEN
        # @see https://github.com/aws/aws-sdk-js/pull/1391
        # @see https://stackoverflow.com/questions/57768714/get-region-from-aws-cli-using-node
        # @see https://stackoverflow.com/questions/31331788/using-aws-cli-what-is-best-way-to-determine-the-current-region
        # the SDK uses `AWS_REGION` and the CLI uses `AWS_DEFAULT_REGION`.  What the !~$@!@~!
      - AWS_DEFAULT_REGION
      - AWS_REGION=${AWS_DEFAULT_REGION}
      - AWS_SDK_LOAD_CONFIG
    volumes:
    - $HOME/.aws/:/root/.aws/:ro
    - ./:/home/code/
